name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - uses: actions/checkout@v7
      - name: CMake
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake
          cmake --build build
